In [1]:
from Scaling import scaling,umax,dmax,emax
import numpy as np
import System
import sympy as sp
sp.init_printing()
from System import system
s = sp.Symbol('s')

In [2]:
sys = system()

In [3]:
sys.poles[0]

[[[-0.00617283950617284],
  [-0.00819672131147541, -0.00291545189504373],
  [-0.00702368692070031 - 0.00753194822192866*I,
   -0.00702368692070031 + 0.00753194822192866*I]],
 [[-0.00505050505050505],
  [-0.00862068965517241, -0.00287356321839080],
  [-0.00754696132596685 - 0.0080709212515236*I,
   -0.00754696132596685 + 0.0080709212515236*I]],
 [[-0.00197628458498024], [-0.00292397660818713], [-0.00526315789473684]]]

In [4]:
sys.zeros[0]

[[[], [0.000157391304347826], []],
 [[], [0.0124731182795699], []],
 [[], [], []]]

In [10]:
sys.Gp(1j*300)

matrix([[  5.69e-06 +6.17e-05j,  -1.10e-05 -1.67e-05j,   1.44e-10 +9.01e-10j],
        [  3.15e-05 -7.24e-07j,   9.82e-06 -7.38e-06j,  -1.71e-09 -7.50e-11j],
        [ -8.61e-06 -1.00e-05j,   8.89e-06 -1.69e-05j,   3.21e-08 +2.34e-07j]])

In [6]:
sys.Gd(2) 

matrix([[  3.83e-102,   1.92e-120,   4.69e-112],
        [  4.08e-038,   1.47e-021,   3.73e-007],
        [ -1.74e-006,  -6.85e-005,   6.01e+001]])

In [9]:
sys.Gp_sym.subs(s,1j*300)

Matrix([
[-3.0110723280011*exp(-41400.0*I)/(1 + 48600.0*I), 218.193646956602*(0.000181 - 345.0*I)*exp(-56100.0*I)/((1 + 36600.0*I)*(1 + 102900.0*I)), -0.774587446695936*exp(-40500.0*I)/(-848556899.0 + 39733.32*I)],
[          -1.872*exp(-10350.0*I)/(1 + 59400.0*I),                8.0*(0.232 - 5580.0*I)*exp(-33900.0*I)/((1 + 34800.0*I)*(1 + 104400.0*I)),                -1.26*exp(-4860.0*I)/(-737122499.0 + 37086.9*I)],
[2.00869593250299*exp(-5310.0*I)/(1 + 151800.0*I),                                       -1.95489157716809*exp(-12990.0*I)/(1 + 102600.0*I),             0.0134735073151149*exp(-40800.0*I)/(1 + 57000.0*I)]])

Matrix([
[-3.0110723280011*exp(-138.0*s)/(162.0*s + 1), 218.193646956602*(-1.15*s + 0.000181)*exp(-187.0*s)/((122.0*s + 1)*(343.0*s + 1)), -0.774587446695936*exp(-135.0*s)/(9428.41*s**2 + 132.4444*s + 1)],
[           -1.872*exp(-34.5*s)/(198.0*s + 1),                 8.0*(-18.6*s + 0.232)*exp(-113.0*s)/((116.0*s + 1)*(348.0*s + 1)),                -1.26*exp(-16.2*s)/(8190.25*s**2 + 123.623*s + 1)],
[ 2.00869593250299*exp(-17.7*s)/(506.0*s + 1),                                      -1.95489157716809*exp(-43.3*s)/(342.0*s + 1),                   0.0134735073151149*exp(-136.0*s)/(190.0*s + 1)]])

In [12]:
sys.De

matrix([[ 0.18,  0.  ,  0.  ],
        [ 0.  ,  5.  ,  0.  ],
        [ 0.  ,  0.  ,  0.22]])

In [16]:
np.array(sys.emax)*sys.De.I

matrix([[ 1.,  1.,  1.]])