In [1]:
from Scaling import scaling,umax,dmax,emax
import numpy as np
import System
import sympy as sp
sp.init_printing(use_latex='mathjaxx')
from System import system

In [2]:
sys = system()

In [45]:
sys.ssRGA

array([[ 1.01, -0.01,  0.01],
       [-0.39,  0.39,  1.  ],
       [ 0.38,  0.63, -0.01]])

above we see the steady state relative gain array (used in decentralized control). Values that are positive and close to 1 represent good pairings. Here we see that Ps1 should be paired with Cc_measured, Ps2 with tank level and Ps3 with temperature. This comes as no surprise given the nature of the system. What is surprising, however is how small the effect of cooling is on manipulating concentration. This system should be easily controlled with decentralized control in absence of disturbances, given that the RGA produces clear, optimal pairings. Ps2 can also be used to control temperature to an extent and Ps1 to control level.

In [4]:
gpgains = np.matrix(sys.gainarrays[0])
gdgains = sys.gainarrays[1]

In [5]:
rga = np.multiply(gpgains,gpgains.I.T)  # hadamard product (element wise mult)

In [6]:
rga

matrix([[ 1.01, -0.01,  0.01],
        [-0.39,  0.39,  1.  ],
        [ 0.38,  0.63, -0.01]])

In [7]:
gpgains

matrix([[-3.01,  0.04, -0.77],
        [-1.87,  1.86, -1.26],
        [ 2.01, -1.95,  0.01]])

In [8]:
gdgains

array([[ 0.78,  0.48,  1.06],
       [ 0.52,  0.96,  0.69],
       [-0.01, -0.01,  0.17]])

Frequency RGA analysis
3x3 system so 3x2x1 = 6 possible pairings


In [9]:
p1 = np.matrix([[1,0,0],
                [0,1,0],
                [0,0,1]])

p2 = np.matrix([[0,1,0],
                [1,0,0],
                [0,0,1]])

p3 = np.matrix([[0,0,1],
                [1,0,0],
                [0,1,0]])

p4 = np.matrix([[1,0,0],
                [0,0,1],
                [0,1,0]])

p5 = np.matrix([[0,0,1],
                [0,1,0],
                [1,0,0]])

p6 = np.matrix([[0,1,0],
                [0,0,1],
                [1,0,0]])

pairs = [p1,p2,p3,p4,p5,p6]


g = np.matrix([[5,4],
               [3,2]])


In [17]:
def rganum(w,pair):
    return np.sum(sys.fRGA(w) - pair)

In [35]:
res = []
w = np.linspace(0,2000,2000)
count = 0
for pair in pairs:
    res.append([])
    for i in w:
        num = rganum(i,pair)
        res[count].append(num)
    count += 1

In [44]:
from matplotlib import pyplot as plot
plot.figure()
for i in res:
    plot.plot(w,np.array(i).real)
plot.show()